spring.docker.compose.enabled=false

management.tracing.sampling.probability=0.1
management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://otel-collector:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://otel-collector:4318/v1/logs

logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=info
logging.level.org.springframework.boot.docker.compose=off