spring.application.name=PhenylalanineCalculatorApi

spring.profiles.active=local,db,secrets
spring.config.import=optional:file:./dummy-config/,optional:file:./local-config/

server.port=8080
server.shutdown=graceful

springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/master.yaml

logging.level.com.keldorn=info